### ISSUE TITLE
Successful report: Lenovo S5 2nd Gen (20JAA009HH)

### ISSUE THREAD

**Issue by dbpalan** [coderobe/VBiosFinder#1]
BIOS successfully extracted from [BIOS Update Utility v1.13 dated 03.11.2017](https://download.lenovo.com/pccbbs/mobiles/r0muj09w.exe)

> $ ./vbiosfinder extract /tmp/r0muj09w.exe 
> output will be stored in '/usr/local/src/VBiosFinder-master/tmp-vbiosfinder'
> checking for ruby... yes
> 
> trying to extract ./r0muj09w.exe
> checking for innoextract... yes
> found innoextract archive
> Extracting "ThinkPad BIOS Update Utility" - setup data version 5.5.7
>  - "app/406E1.PAT" (79 KiB)
>  - "app/406E2.PAT" (84 KiB)
>  - "app/406E3.PAT" (89 KiB)
>  - "app/BCP.evs" (160 B)
>  - "app/BIOS_LOGO.TXT" (2.21 KiB)
>  - "app/bootx64.efi" (1.38 MiB)
>  - "app/chklogo.exe" (3.5 KiB)
>  - "app/chklogo.exe.config" (239 B)
>  - "app/DosFlash.exe" (465 KiB)
>  - "app/Instruction US - BIOS flash USB memory key.txt" (1.63 KiB)
>  - "app/mkusbkey.bat" (1.34 KiB)
>  - "app/SHELLFLASH.EFI" (22.8 KiB)
>  - "app/WinFlash32.exe" (411 KiB)
>  - "app/WinFlash32s.exe" (411 KiB)
>  - "app/WinFlash64.exe" (397 KiB)
>  - "app/WinFlash64s.exe" (397 KiB)
>  - "app/wininfo.exe" (80.5 KiB)
>  - "app/wininfo64.exe" (89 KiB)
>  - "app/winuptp.exe" (3.31 MiB)
>  - "app/winuptp64.exe" (4.66 MiB)
>  - "app/32bit/tpnflhlp.sys" (25.8 KiB)
>  - "app/64bit/tpnflhlp.sys" (25.8 KiB)
>  - "app/R0MET36W/$0AR0M00.FL1" (6.97 MiB)
> Done
> ...
> trying to extract ./app/R0MET36W/$0AR0M00.FL1
> checking for innoextract... yes
> not extractable with innoextract
> checking for upx... yes
> not extractable with upx
> checking for 7z... yes
> not extractable with 7z
> checking for UEFIDump... yes
> parseVolumeHeader: unaligned volume
> parseVolumeHeader: unaligned volume
> parseVolumeHeader: unaligned volume
> parseVolumeHeader: unaligned volume
> parseVolumeHeader: unaligned volume
> parseVolumeHeader: unaligned volume
> parseVolumeHeader: unaligned volume
> parseVolumeHeader: unaligned volume
> parsePadFileBody: non-UEFI data found in pad-file
> found UEFI image
> extracted. filtering modules...
> got 4266 modules
> finding vbios
> 4 possible candidates
> checking for rom-parser... yes
> Found VBIOS for device 10de:1c8c!
> Found VBIOS for device 8086:0406!
> Found VBIOS for device 10de:139b!
> Found VBIOS for device 10de:1c8e!
> Job done. Extracted files can be found in /usr/local/src/VBiosFinder-master/tmp-vbiosfinder/../output
> Cleaning up garbage

[VBIOS files extracted for further verification
](https://www.dropbox.com/sh/aiz2kp8cnorcfgb/AAB3oHUMYxKiypJ71pZ55gq-a?dl=0
)

OS: Debian Stretch
ID of the onboard GeForce 1050 Ti is 10de:1c8c
Official Packages: build-essential cmake ruby innoextract upx-ucl
Self build: rom-parser, UEFIDump (move to /usr/local/bin after built)

[Workaround for `cannot open output file UEFIDump: Is a directory` when building UEFIDump](https://github.com/LongSoft/UEFITool/issues/107#event-1468739949)

**Comment by coderobe** [comment]
The VBIOS files appear to be valid.
Thanks for your report! I'll add your device to the list of tested devices in the README.
