### ISSUE TITLE
Zbook not supported?

### ISSUE THREAD

**Issue by silverchairbg** [coderobe/VBiosFinder#14]
Hi,

I tried to extract the VBIOS from Zbook G5.
I get the following output:

`hp@HP:/mnt/c/Users/hp/Desktop/VBiosFinder$ ./vbiosfinder extract /mnt/c/Users/hp/Desktop/VBiosFinder/Q70_010700.bin
output will be stored in '/mnt/c/Users/hp/Desktop/VBiosFinder/tmp-vbiosfinder'
checking for ruby... yes

checking for innoextract... yes
checking for upx... yes
checking for 7z... yes
trying to extract ./Q70_010700.bin
extracting uefi data
trying to extract ./Q70_010700.bin
found UEFIExtract archive
trying to extract ./mkmf.log
found UEFIExtract archive
filtering for modules...
got 3034 modules
finding vbios
no candidates found :(
input contains uefi data but no vbios could be found
the vbios might not be baked into the input!
Cleaning up garbage
Traceback (most recent call last):
        1: from /mnt/c/Users/hp/Desktop/VBiosFinder/src/cli.rb:27:in `block in extract'
/usr/lib/ruby/2.5.0/fileutils.rb:629:in `remove_entry_secure': parent directory is world writable, FileUtils#remove_entry_secure does not work; abort: "/mnt/c/Users/hp/Desktop/VBiosFinder/tmp-vbiosfinder" (parent directory mode 40777) (ArgumentError)`

I got the image from here: https://ftp.hp.com/pub/softpaq/sp95501-96000/sp95877.exe

vbioses used to be there on these laptops, maybe using tool wrong way?

**Comment by coderobe** [comment]
I checked manually and that bios update does not seem to contain a vbios
