### ISSUE TITLE
Custom saving needs improvement

### ISSUE THREAD

**Issue by stzokev** [coderobe/VBiosFinder#20]
Whenever it cannot determine vbios type, it seems to only take into consideration the name of the image for the saved file. I've hit a case when there are multiple instances of the same name, so I end up with a single file e.g.:

can't determine vbios type of body.bin, saving as 'vbios_unknown_body.bin'
can't determine vbios type of body.bin, saving as 'vbios_unknown_body.bin'
can't determine vbios type of body.bin, saving as 'vbios_unknown_body.bin'
can't determine vbios type of body.bin, saving as 'vbios_unknown_body.bin'

Maybe a random UUID should be used for the file name? You can reproduce this with Zbook 17 G2 bios.

**Comment by coderobe** [comment]
Should be fixed now
