### ISSUE TITLE
Duplicate files should not overwrite existing files

### ISSUE THREAD

**Issue by coderobe** [coderobe/VBiosFinder#30]
When saving files, append `_{NUM}` to the filename before the file extension where NUM is the number of the duplicate

e.g.: `vbios_dead:beef.bin` should become `vbios_dead:beef_2.bin` when the former already exists in the path, and `3` when the latter exists, and so on

Relevant issues:
https://github.com/coderobe/VBiosFinder/issues/27
https://github.com/coderobe/VBiosFinder/issues/22
https://github.com/coderobe/VBiosFinder/issues/20

**Comment by Pey-crypto** [comment]
I have worked on it and posted a pull request..could you check it up

**Comment by coderobe** [comment]
thanks! i will take a look once i get the time

**Comment by coderobe** [comment]
fixed by https://github.com/coderobe/VBiosFinder/pull/31
