### ISSUE TITLE
Terrapin Command not found error

### ISSUE THREAD

**Issue by EataPanini** [coderobe/VBiosFinder#36]
Hi, when i try to run the scrip it gives me /usr/lib/ruby/gems/2.7.0/gems/terrapin-0.6.0/lib/terrapin/command_line.rb:82:in `run': Terrapin::CommandNotFoundError (Terrapin::CommandNotFoundError), i'm on void and i installed all of the dependencies.

**Comment by EataPanini** [comment]
works on arch

**Comment by EataPanini** [comment]
nevermind

**Comment by coderobe** [comment]
This hints at a missing dependency. Are you sure all of the dependencies are present and reachable in your $PATH?
Is this the full output, or is there anything else?

**Comment by EataPanini** [comment]
> This hints at a missing dependency. Are you sure all of the dependencies are present and reachable in your $PATH?
> Is this the full output, or is there anything else?

Yep im sure ive installed everything

**Comment by EataPanini** [comment]
Traceback (most recent call last):
	12: from _init.rb:7:in `<main>'
	11: from /home/panini/KVM/VBiosFinder/vendor/bundle/ruby/2.7.0/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
	10: from /home/panini/KVM/VBiosFinder/vendor/bundle/ruby/2.7.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
	9: from /home/panini/KVM/VBiosFinder/vendor/bundle/ruby/2.7.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
	8: from /home/panini/KVM/VBiosFinder/vendor/bundle/ruby/2.7.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
	7: from /home/panini/KVM/VBiosFinder/src/cli.rb:36:in `extract'
	6: from /home/panini/KVM/VBiosFinder/src/methods.rb:44:in `run'
	5: from /home/panini/KVM/VBiosFinder/src/methods.rb:44:in `each'
	4: from /home/panini/KVM/VBiosFinder/src/methods.rb:46:in `block in run'
	3: from /home/panini/KVM/VBiosFinder/src/extraction.rb:8:in `attempt'
	2: from /home/panini/KVM/VBiosFinder/src/extraction.rb:8:in `call'
	1: from /home/panini/KVM/VBiosFinder/src/extract-uefi.rb:20:in `uefi'
/home/panini/KVM/VBiosFinder/vendor/bundle/ruby/2.7.0/gems/terrapin-0.6.0/lib/terrapin/command_line.rb:82:in `run': Terrapin::CommandNotFoundError (Terrapin::CommandNotFoundError)

and this is the whole error i think

**Comment by coderobe** [comment]
you're lacking UEFIExtract.

**Comment by EataPanini** [comment]
> you're lacking UEFIExtract.

oh my god  im stupid i was trying to use UEFITOOL instead of UEFIExtract also works for the thinkpad T520
