### ISSUE TITLE
If it's linux tool, why instruction says to run exe?

### ISSUE THREAD

**Issue by monotwist** [coderobe/VBiosFinder#5]
I mean this: "Run ./vbiosfinder extract /path/to/bios_update.exe to attempt an extraction"

**Comment by coderobe** [comment]
it does not run run any `exe`, and the instructions also do not tell you to run such an `exe`

**Comment by monotwist** [comment]
Then what role does exe play?

**Comment by monotwist** [comment]
рерк

**Comment by monotwist** [comment]
> it does not run run any `exe`, and the instructions also do not tell you to run such an `exe`

![image](https://user-images.githubusercontent.com/25460660/68767753-50166d80-0632-11ea-84ba-bacc37a71ba2.png)
